<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="favicon.ico" />
    <?= $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
</head>

<body class="app">
    <div class="app-content">
        <main class="container">
            <?= $this->content ?>
        </main>
    </div>

    <footer class="app-footer">
        <div class="container">
            <hr />
            <p class="copyright">
                &copy; <?= date('Y') ?> All rights reserved.
            </p>
        </div>
    </footer>
    <?= $this->headScript() ?>
    <?= $this->inlineScript() ?>
</body>

</html>